GET http://localhost:3000/lists 

###
GET http://localhost:3000/lists/2

###
POST http://localhost:3000/lists
Content-Type: application/json

{
  "name": "My List"
}


###
GET http://localhost:8000/lists
